# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          dependency-graph: generate-and-submit
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build

      - name: Get jar names
        id: get_jars
        run: |
          cd build/libs
          JAR_NAME=$(ls *.jar | grep -v sources)
          SOURCES_JAR_NAME=$(ls *.jar | grep sources)
          echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV
          echo "SOURCES_JAR_NAME=$SOURCES_JAR_NAME" >> $GITHUB_ENV

      - name: Upload jar
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.JAR_NAME }}
          archive: false
          path: build/libs/${{ env.JAR_NAME }}

      - name: Upload sources jar
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.SOURCES_JAR_NAME }}
          archive: false
          path: build/libs/${{ env.SOURCES_JAR_NAME }}